flathub/app.zen_browser.zen

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.7.1b.

🚀 Update to version 1.7.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.7.2b.

🚀 Update to version 1.7.2b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.7.4b.

🚀 Update to version 1.7.4b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.7.5b.

🚀 Update to version 1.7.5b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.8b.

🚀 Update to version 1.8b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.8.1b.

🚀 Update to version 1.8.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.8.2b.

🚀 Update to version 1.8.2b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.9b.

🚀 Update to version 1.9b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.9.1b.

🚀 Update to version 1.9.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.10b.

🚀 Update to version 1.10b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.10.1b.

🚀 Update to version 1.10.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.10.2b.

🚀 Update to version 1.10.2b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.10.3b.

🚀 Update to version 1.10.3b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.11b.

🚀 Update to version 1.11b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.11.1b.

🚀 Update to version 1.11.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.11.2b.

🚀 Update to version 1.11.2b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.11.3b.

🚀 Update to version 1.11.3b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.11.4b.

🚀 Update to version 1.11.4b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.11.5b.

🚀 Update to version 1.11.5b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.12b.

🚀 Update to version 1.12b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.12.1b.

🚀 Update to version 1.12.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.12.4b.

🚀 Update to version 1.12.4b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.13.1b.

🚀 Update to version 1.13.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.14b.

🚀 Update to version 1.14b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.14.2b.

🚀 Update to version 1.14.2b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.14.4b.

🚀 Update to version 1.14.4b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.14.9b.

🚀 Update to version 1.14.9b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.14.10b.

🚀 Update to version 1.14.10b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.14.11b.

🚀 Update to version 1.14.11b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.15.1b.

🚀 Update to version 1.15.1b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.15.2b.

🚀 Update to version 1.15.2b

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.15.3b.

🚀 Update to version 1.15.3b

---

app.zen_browser.zen.yml

Reverts flathub/app.zen_browser.zen#92

Revert "🚀 Update to version 1.15.3b"

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.15.5b.

Update to version `1.15.5b`

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.15.4b.

Update to version `1.15.4b`

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.16b.

Update to version `1.16b`

---

app.zen_browser.zen.yml

This PR updates the Zen Browser Flatpak package to version 1.16.2b.

Update to version `1.16.2b`
